### ISSUE TITLE
UME 有多处依赖冲突，还未支持 Flutter 2.2.3 吗？或者计划什么时候将依赖升级到最新版？

### ISSUE THREAD

**Issue by yrom** [bytedance/flutter_ume#2]
## What's your question 你遇到了什么问题
依赖冲突，如：device_info，vm_service，platform....

### Flutter doctor

``` bash
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

### UME and kits version UME 及插件包版本

```
dependencies:
  device_info: ^2.0.2
  path_provider: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.2.0
  build_runner: ^1.10.0
  vm_service: ^7.1.0
  flutter_ume: ^0.1.0
  flutter_ume_kit_ui: ^0.1.0
  flutter_ume_kit_device: ^0.1.0
  flutter_ume_kit_perf: ^0.1.0
  flutter_ume_kit_console: ^0.1.0
```

**Comment by smileShirely** [comment]
@yrom 你好，由于 vm_service 的 7.x.x 版本、path_provider的 2.x.x 版本、device_info 的 2.x.x 版本都是 nullsafety 的，flutter_ume 直接依赖这些组件的高版本，会导致低版本 Flutter 工程无法使用。我按照您的依赖列表创建了一个测试工程，通过 `dependency_overrides` 是可以通过覆盖版本在 no-sound-null-safety 模式下使用的。具体 pubspec.yaml 内容请见：
``` yaml
name: issue_test_0
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.2
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.2.0
  build_runner: ^1.10.0
  vm_service: ^7.1.0
  flutter_ume: ^0.1.0+1
  flutter_ume_kit_ui: ^0.1.0
  flutter_ume_kit_device: ^0.1.0
  flutter_ume_kit_perf: ^0.1.0
  flutter_ume_kit_console: ^0.1.0
  flutter_ume_kit_show_code: ^0.1.0

dependency_overrides:
  vm_service: ^7.1.0
  device_info: ^2.0.2
  path_provider: ^2.0.2
  platform: ^3.0.0

flutter:
  uses-material-design: true
```
另外flutter_ume 开源版的 nullsafety 适配工作正在加紧开发中，近期发布，感谢关注。
