### ISSUE TITLE
请问网络监控什么时候可以开源

### ISSUE THREAD

**Issue by fg2q1q3q** [bytedance/flutter_ume#3]
你好，请问网络监控模块什么时候可以开源，很好奇是如何Hook实现的？期待更新

**Comment by smileShirely** [comment]
> 你好，请问网络监控模块什么时候可以开源，很好奇是如何Hook实现的？期待更新

@fg2q1q3q 你好。内部版是基于 transformer 的 hook 实现的请求通用拦截与 mock 方案，目前计划在开源版上会以其他形式支持。上层可复用内部版的请求管理和 mock 的通用逻辑，底层替换掉。也欢迎如果有请求拦截的方案可以贡献给社区一起讨论，争取支持通用的请求拦截

**Comment by smileShirely** [comment]
#16 Merged. 

该 PR 支持来自 Dio 网络库的请求监控。请问你的 App 使用的是什么网络组件？我们可以考虑定向支持。

试用 #16 ，修改 pubspec.yaml 中内容：

``` yaml
dependency_overrides:
  flutter_ume:
    git: https://github.com/bytedance/flutter_ume.git
    ref: develop_nullsafety
```
